name: mdpi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - imutils=0.5.4
  - numpy=2.3.3
  - opencv=4.11.0
  - pandas=2.3.2
  - scikit-image=0.25.2
  - tensorflow=2.18.0
  - scikit-learn=1.7.1
  - flask=3.1.2
  - gunicorn=23.0.0
